version: "3.9"
services:
 chess-api-service:
  image: robbie013123/api-eindproject
  ports:
    - "8000:8000"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume:
